backend:
  name: git-gateway
  repo: jesusortizc18-coder/renacer-web
  branch: main

media_folder: "images/uploads" # Donde se guardarán las fotos que ella suba
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Catálogo de Productos"
    folder: "data/productos" # Aquí se guardará la info de cada pieza
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre de la Pieza", name: "title", widget: "string" }
      - {
          label: "Categoría",
          name: "categoria",
          widget: "select",
          options: ["Pulseras", "Collares", "Zarcillos", "Anillos"],
        }
      - { label: "Imagen", name: "image", widget: "image" }
      - {
          label: "Precio (Opcional)",
          name: "precio",
          widget: "string",
          required: false,
        }


